### ISSUE TITLE
Access request to Repo

### ISSUE THREAD

**Issue by tiadal** [brishnafarahi/safe_signs_limited#1]
Hello @brishnafarahi, hello @KingsleyOdiboh,

I made a mistake, because I had 2 git accounts. Please add @tiadal and @AlbertV11 (the other person in the group) as well. Sorry for the troubles.

Thanks a lot, 
Mattia

**Comment by brishnafarahi** [comment]
hey there, 
would you please send me your  exact email address so that i add you

**Comment by brishnafarahi** [comment]
Hi @tiadal ,
i have grant you the access everything should work now.
Regards
Brishna

**Comment by KingsleyOdiboh** [comment]
Issue has been resolved.

**Comment by brishnafarahi** [comment]
i am not sure if we have given access to the right people, in the table uploaded from Mr. Reyes there is another group that is developer for our website. and we are the developers for the website of team @tiadal

**Comment by KingsleyOdiboh** [comment]
Very correct! Chaudhary-Ghazlan are the developers for the project and not @tiadal and @AlbertV11. I guess you have to retract access.

**Comment by tiadal** [comment]
Hello, you are both right, now the table of the prof shows something else, or I copied to wrong. Please delete access. 

Sorry for the inconvenience,
Mattia
