### ISSUE TITLE
Overview of the website

### ISSUE THREAD

**Issue by obadaghozlan** [brishnafarahi/safe_signs_limited#10]
Greetings,

we would appreciate it if you could take a quick look at the website where you can find in the develop branch.
I would also like to ask about what should the page Consultancy and Certification contain.

best Regards.

**Comment by KingsleyOdiboh** [comment]
Sample information for the consultancy page have been included to the readme file.

**Comment by brishnafarahi** [comment]
all the information's are in the readme file, if there is still confusion let us know.
