### ISSUE TITLE
Products

### ISSUE THREAD

**Issue by obadaghozlan** [brishnafarahi/safe_signs_limited#5]
Hey, i have a question about the products webpage, i added 9 products of the traffic signs and 9 products of the warning sign.
would you like me to add all of them? or would that be enough?
![products](https://user-images.githubusercontent.com/45075335/103457368-02116d00-4cff-11eb-83db-321bbfb09443.PNG)

**Comment by KingsleyOdiboh** [comment]
It's interesting that all the products are of the same category in the design. You probably should check the readme file again.

**Comment by obadaghozlan** [comment]
hey Kingsley thanks for your feedback, but this doesn't answer the question. Please note that this was 7 days ago and it's just a prototype.
@KingsleyOdiboh can you please check the other issue 
Thanks

**Comment by KingsleyOdiboh** [comment]
Sorry! Unfortunately, the last part of my message wasn't included and I just noticed. Yes, you can leave it this way for now. Other adjustments can be made in the future. Thanks
