### ISSUE TITLE
Feedback for About Us

### ISSUE THREAD

**Issue by chaudhary6-1** [brishnafarahi/safe_signs_limited#6]
![about-us](https://user-images.githubusercontent.com/75631983/103459970-fa5bc380-4d12-11eb-85fc-c03365be135b.png)

**Comment by KingsleyOdiboh** [comment]
Great layout guys! Can we see how it looks with a brighter color scheme?

**Comment by chaudhary6-1** [comment]
![about-us](https://user-images.githubusercontent.com/75631983/103472777-cd022a80-4d91-11eb-89ad-c9c43feeda56.png)

I personally finds brighter color scheme really irritating for the eye and we tried with white and blue as proposed in description but they wont really match together as well. That is why we want to go with something more comfortable for the eye.

**Comment by chaudhary6-1** [comment]
It would be great if we could use the color scheme as seen in the first photo of this issue.
